# Import and Load

In [1]:
# Data Analysis #
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import re

# Graphics #
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')
#import geopandas
#from shapely.geometry import Point
%matplotlib inline


# Display up to 60 columns of a dataframe
pd.set_option('display.max_columns', 60)

# Set default font size
#plt.rcParams['font.size'] = 24

# ML packages #

# Splitting data into training and testing

In [90]:
# Data #
tag = 'Healthy_Aging_Data.csv'
raw_df = pd.read_csv(tag)
raw_df.sample(5)

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Response,Data_Value_Unit,DataValueTypeID,Data_Value_Type,Data_Value,Data_Value_Alt,Data_Value_Footnote_Symbol,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,Sample_Size,StratificationCategory1,Stratification1,StratificationCategory2,Stratification2,StratificationCategory3,Stratification3,GeoLocation,ClassID,TopicID,QuestionID,ResponseID,LocationID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3,Report
33930,2016,2016,OH,Ohio,BRFSS,Screenings and Vaccines,Pap test within past 3 years,Percentage of older adult women with an intact...,NaN,%,PRCTG,Percentage,78.1,NaN,NaN,NaN,72.2,83.1,NaN,Age Group,60-64 years,NaN,NaN,NaN,NaN,"(40.06021014100048, -82.40426005599966)",C03,TSC03,Q20,NaN,39,AGE,6064,NaN,NaN,NaN,NaN,NaN
14738,2012,2012,AL,Alabama,BRFSS,Screenings and Vaccines,Colorectal cancer screening,Percentage of older adults who had either a ho...,NaN,%,PRCTG,Percentage,75.0,NaN,NaN,NaN,72.8,77.0,NaN,Age Group,65 years or older,NaN,NaN,NaN,NaN,"(32.84057112200048, -86.63186076199969)",C03,TSC02,Q15,NaN,1,AGE,65PLUS,NaN,NaN,NaN,NaN,NaN
19714,2011,2011,WY,Wyoming,BRFSS,Nutrition/Physical Activity/Obesity,Obesity,Percentage of older adults who are currently o...,NaN,%,PRCTG,Percentage,32.2,NaN,NaN,NaN,27.1,37.9,NaN,Age Group,60-64 years,NaN,NaN,NaN,NaN,"(43.23554134300048, -108.10983035299967)",C02,TNC04,Q13,NaN,56,AGE,6064,NaN,NaN,NaN,NaN,NaN
7540,2013,2013,OR,Oregon,BRFSS,Screenings and Vaccines,Mammogram within past 2 years,Percentage of older adult women who have recei...,NaN,%,PRCTG,Percentage,NaN,NaN,~,No Data Available,NaN,NaN,NaN,Age Group,55-59 years,NaN,NaN,NaN,NaN,"(44.56744942400047, -120.15503132599969)",C03,TSC01,Q12,NaN,41,AGE,5559,NaN,NaN,NaN,NaN,NaN
17537,2012,2012,FL,Florida,BRFSS,Overall Health,Recent activity limitations in past month,Mean number of days with activity limitations ...,NaN,Number,MEAN,Mean,8.7,NaN,NaN,NaN,7.1,10.3,NaN,Age Group,55-59 years,NaN,NaN,NaN,NaN,"(28.932040377000476, -81.92896053899966)",C01,TOC03,Q35,NaN,12,AGE,5559,NaN,NaN,NaN,NaN,NaN

# Data Cleaning and Transforming

>For the sake of this project, only patients with Cognitive Decline problems will be extracted from the data. This information lie under Class column of dataset. `cognitive_df` will represent the partial data that has aforementioned property. 

>The `dataframe.info` method is a quick way to assess the data by displaying the data types of each column and the number of non-missing values.

>After checking out df.info() function, it is better to drop empty columns. 

>Data Value and its unit is important when statistical analysis is to be employed. We have to make sure units and types are consistent. To check that we will have to investigate columns that have numerical values except year columns.

## Filter by Disease/Diagnosis

In [91]:
raw_df['Question'].unique()

array(['Percentage of older adults who report having a disability',
       'Percentage of older adults who are experiencing frequent mental distress',
       'Percentage of older adults who have fallen and sustained an injury within last year',
       'Percentage of older adults who report having lost 5 or fewer teeth due to decay or gum disease',
       'Percentage of older adults with a lifetime diagnosis of depression',
       'Physically unhealthy days (mean number of days in past month)',
       'Percentage of at risk adults (have diabetes, asthma, cardiovascular disease or currently smoke) who ever had a pneumococcal vaccine',
       'Percentage of older adults who reported binge drinking within the past 30 days',
       'Percentage of older adults getting sufficient sleep (>6 hours)',
       'Percentage of older adults who are currently obese, with a body mass index (BMI) of 30 or more',
       'Percentage of older adult men who are up to date with select clinical preventive services',
       'Percentage of older adult women who have received a mammogram within the past 2 years',
       'Mean number of days with activity limitations in the past month',
       'Percentage of older adults who had either a home blood stool test within the past year or a sigmoidoscopy or colonoscopy within the past 10 years',
       'Percentage of older adults who have smoked at least 100 cigarettes in their entire life and still smoke every day or some days',
       'Percentage of older adults who have not had any leisure time physical activity in the past month',
       'Percentage of older adult women with an intact cervix who had a Pap test within the past 3 years',
       'Percentage of older adults who reported influenza vaccine within the past year',
       'Percentage of older adults without diabetes who reported a blood sugar or diabetes test within 3 years',
       'Percentage of older adults who self-reported that their health is "fair" or "poor"',
       'Percentage of older adults who self-reported that their health is "good", "very good", or "excellent"',
       'Percentage of older adults who are eating 2 or more fruits daily',
       'Percentage of older adults who are eating 3 or more vegetables daily',
       'Percentage of older adults who have been told they have high blood pressure who report currently taking medication for their high blood pressure',
       'Percentage of older adults who had a cholesterol screening within the past 5 years',
       'Percentage of older adults who have ever been told by a health professional that they have high blood pressure',
       'Percentage of older adults who reported subjective cognitive decline or memory loss that is happening more often or is getting worse in the preceding 12 months',
       'Percentage of older adults who reported subjective cognitive decline or memory loss that interferes with their ability to engage in social activities or household chores',
       'Percentage of older adult women who are up to date with select clinical preventive services',
       'Percentage of older adults who provided care for a friend or family member within the past month',
       'Percentage of older adults currently not providing care who expect to provide care for someone with health problems in the next two years',
       'Percentage of older adults who provided care to a friend or family member for six months or more',
       'Average of 20 or more hours of care per week provided to a friend or family member',
       'Percentage of older adults who provided care for someone with dementia or other cognitive impairment within the past month',
       'Percentage of older adults with subjective cognitive decline or memory loss who reported talking with a health care professional about it',
       'Percentage of older adults who reported that as a result of subjective cognitive decline or memory loss that they need assistance with day-to-day activities'],
      dtype=object)

>Cognitive decline is reported under two main categories one that is from the patient-self and the other the care giver to the person with cognitive illness. Since we are not given if these are the same or distinct patients in these two class, to prevent overlapping we go with only one class which is here being Cognitive class.

In [92]:
filt_cognitive = raw_df['Class'] == 'Cognitive Decline'
cognitive_df = raw_df[filt_cognitive]

In [93]:
def drop_empty_columns(df):
    ''' Drop Empty Columns From A DataFrame'''
    all_empty = df.shape[0]
    to_be_dropped = [
        cols for cols in df.columns if df[cols].isnull().sum() == all_empty]
    print(to_be_dropped)
    df = df.drop(columns=to_be_dropped)
    return df

In [94]:
cognitive_df = drop_empty_columns(cognitive_df)
cognitive_df.info()

['Response', 'Data_Value_Alt', 'Sample_Size', 'StratificationCategory3', 'Stratification3', 'ResponseID', 'StratificationCategoryID3', 'StratificationID3', 'Report']
<class 'pandas.core.frame.DataFrame'>
Int64Index: 3696 entries, 21919 to 42703
Data columns (total 29 columns):
YearStart                     3696 non-null int64
YearEnd                       3696 non-null int64
LocationAbbr                  3696 non-null object
LocationDesc                  3696 non-null object
Datasource                    3696 non-null object
Class                         3696 non-null object
Topic                         3696 non-null object
Question                      3696 non-null object
Data_Value_Unit               3696 non-null object
DataValueTypeID               3696 non-null object
Data_Value_Type               3696 non-null object
Data_Value                    2078 non-null float64
Data_Value_Footnote_Symbol    2046 non-null object
Data_Value_Footnote           2046 non-null object
Low_Confidence_Limit          2078 non-null float64
High_Confidence_Limit         2078 non-null float64
StratificationCategory1       3696 non-null object
Stratification1               3696 non-null object
StratificationCategory2       392 non-null object
Stratification2               392 non-null object
GeoLocation                   3024 non-null object
ClassID                       3696 non-null object
TopicID                       3696 non-null object
QuestionID                    3696 non-null object
LocationID                    3696 non-null int64
StratificationCategoryID1     3696 non-null object
StratificationID1             3696 non-null object
StratificationCategoryID2     392 non-null object
StratificationID2             392 non-null object
dtypes: float64(3), int64(3), object(23)
memory usage: 866.2+ KB

>Apparently, this data could give us demographic features of Cognitive Impariments based on location and the age group, gender, ethnicity information of patients. 



> `TopicID` represents the description of the patient reasoning why the patient is considered having Cognitive Decline diagnosis. `ClassID` is a unique identifier for the Class Column or it is a placeholder for the Cognitive Decline diagnosis.

In [95]:
raw_df.loc[raw_df['Class'] == 'Cognitive Decline']['Topic'].unique()

array(['Subjective cognitive decline or memory loss among older adults',
       'Functional difficulties associated with subjective cognitive decline or memory loss among older adults',
       'Talked with health care professional about subjective cognitive decline or memory loss',
       'Need assistance with day-to-day activities because of subjective cognitive decline or memory loss'],
      dtype=object)

## Check Data Units

>Data Values are percentage format that represent the percantage of certain group of people in some location within certain time period. This percentage values unfortunately do not always include reporst coming from all states. This data could provide us to see how common is congitive impariment in which states and if there is a decline or not in the ratio of patients. Ww will have to first get rid of those NaN values in Data_Values column if NaN values belong to different states in different year. In other words, if the statistic belongs to the same state for the same year we may have a chance to impute those with using mean or some other statistic.

>As for the feature selection here, we need only `Data_Value` column among others above. Let's Drop others from the dataframe.

In [96]:
check_units = [col for col in cognitive_df if col.startswith('Data')]
cognitive_df[check_units].sample(10)

,Datasource,Data_Value_Unit,DataValueTypeID,Data_Value_Type,Data_Value,Data_Value_Footnote_Symbol,Data_Value_Footnote
40098,BRFSS,%,PRCTG,Percentage,41.7,NaN,NaN
36770,BRFSS,%,PRCTG,Percentage,NaN,~,No Data Available
22196,BRFSS,%,PRCTG,Percentage,NaN,~,No Data Available
30476,BRFSS,%,PRCTG,Percentage,11.0,#,Fewer than 50 States reporting
40080,BRFSS,%,PRCTG,Percentage,29.2,NaN,NaN
36043,BRFSS,%,PRCTG,Percentage,11.0,NaN,NaN
40651,BRFSS,%,PRCTG,Percentage,45.5,NaN,NaN
40411,BRFSS,%,PRCTG,Percentage,NaN,~,No Data Available
42038,BRFSS,%,PRCTG,Percentage,54.4,NaN,NaN
36425,BRFSS,%,PRCTG,Percentage,47.8,NaN,NaN

In [97]:
if 'Data_Value' in check_units:
    check_units.remove('Data_Value')
    cognitive_df = cognitive_df.drop(columns=check_units)

cognitive_df.sample(5)

,YearStart,YearEnd,LocationAbbr,LocationDesc,Class,Topic,Question,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,StratificationCategory1,Stratification1,StratificationCategory2,Stratification2,GeoLocation,ClassID,TopicID,QuestionID,LocationID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2
40704,2015,2016,VT,Vermont,Cognitive Decline,Talked with health care professional about sub...,Percentage of older adults with subjective cog...,51.0,35.6,66.2,Age Group,60-64 years,NaN,NaN,"(43.62538123900049, -72.51764079099962)",C06,TCC04,Q42,50,AGE,6064,NaN,NaN
28935,2015,2015,US,"United States, DC & Territories",Cognitive Decline,Functional difficulties associated with subjec...,Percentage of older adults who reported subjec...,31.2,28.7,33.8,Age Group,65 years or older,NaN,NaN,NaN,C06,TCC02,Q31,59,AGE,65PLUS,NaN,NaN
28605,2015,2015,TN,Tennessee,Cognitive Decline,Subjective cognitive decline or memory loss am...,Percentage of older adults who reported subjec...,12.4,9.0,16.8,Age Group,55-59 years,NaN,NaN,"(35.68094058000048, -85.77449091399967)",C06,TCC01,Q30,47,AGE,5559,NaN,NaN
40393,2015,2016,OH,Ohio,Cognitive Decline,Need assistance with day-to-day activities bec...,Percentage of older adults who reported that a...,32.2,21.7,44.9,Age Group,55-59 years,NaN,NaN,"(40.06021014100048, -82.40426005599966)",C06,TCC03,Q41,39,AGE,5559,NaN,NaN
40545,2015,2016,CA,California,Cognitive Decline,Talked with health care professional about sub...,Percentage of older adults with subjective cog...,NaN,NaN,NaN,Age Group,50-54 years,NaN,NaN,"(37.63864012300047, -120.99999953799971)",C06,TCC04,Q42,6,AGE,5054,NaN,NaN

## More Transformation and Dropping

In [98]:
# Split GeoLocation into two series Longitude and Latitude, clean the brackets and then make float type
cognitive_df['Longitude'], cognitive_df['Latitude'] = cognitive_df.GeoLocation.str.strip('(').str.split(',', expand=True)[0].astype(float), \
    cognitive_df.GeoLocation.str.strip(')').str.split(
        ',', expand=True)[1].astype(float)

In [99]:
to_drop = ['GeoLocation',
          'StratificationID1',
          'QuestionID',
          'LocationID',
          'LocationAbbr',
          'ClassID',
          'YearEnd',
          'StratificationCategoryID1',
          'StratificationCategoryID2',
          'StratificationID2',
          'StratificationCategory1',
          'StratificationCategory2'
          ]
cognitive_df_clean = cognitive_df.drop(columns=to_drop)
cognitive_df_clean.isnull().sum()

YearStart                   0
LocationDesc                0
Class                       0
Topic                       0
Question                    0
Data_Value               1618
Low_Confidence_Limit     1618
High_Confidence_Limit    1618
Stratification1             0
Stratification2          3304
TopicID                     0
Longitude                 672
Latitude                  672
dtype: int64

In [100]:
cognitive_df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3696 entries, 21919 to 42703
Data columns (total 13 columns):
YearStart                3696 non-null int64
LocationDesc             3696 non-null object
Class                    3696 non-null object
Topic                    3696 non-null object
Question                 3696 non-null object
Data_Value               2078 non-null float64
Low_Confidence_Limit     2078 non-null float64
High_Confidence_Limit    2078 non-null float64
Stratification1          3696 non-null object
Stratification2          392 non-null object
TopicID                  3696 non-null object
Longitude                3024 non-null float64
Latitude                 3024 non-null float64
dtypes: float64(5), int64(1), object(7)
memory usage: 404.2+ KB

## Missing Values

>Now that we have the correct column datatypes, we can start analysis by looking at the percentage of missing values in each column. Missing values are fine when we do Exploratory Data Analysis, but they will have to be filled in for machine learning methods.

>Credits to this function used in making of the table [below: Will Koehrsen](https://towardsdatascience.com/a-complete-machine-learning-walk-through-in-python-part-one-c62152f39420)

>If the column has a high percentage of missing values it will not help explaining the response value therefore it is better to drop that column(s). Above $50\%$ is a good cut off value for determining if the column should be kept or not.

In [101]:
def missing_values_table(df):
    '''Calculate Missing Values of Each Column'''
    # Total missing amount in each feature /series type
    missing_value = df.isnull().sum()

    # Percentage of that missing values in its column /series type
    miss_percent = 100*missing_value/df.shape[0]

    # Make a table of calculated fields /will make dataframe
    table = pd.concat([missing_value, miss_percent], axis=1).rename(
        columns={0: 'Missing Values', 1: '% of Total Values'})

    # Sort by percentages column
    table.sort_values(by=['% of Total Values'], ascending=False,
                      inplace=True)

    # Print Summary Information
    print('\nThe DataFrame has ' + str(df.shape[1]) + ' columns.\n'
          'There are ' + str(table.shape[0]) + ' columns that have missing values')

    return table


missing_values_table(cognitive_df_clean)

The DataFrame has 13 columns.
There are 13 columns that have missing values

                       Missing Values  % of Total Values
Stratification2                  3304          89.393939
Data_Value                       1618          43.777056
Low_Confidence_Limit             1618          43.777056
High_Confidence_Limit            1618          43.777056
Longitude                         672          18.181818
Latitude                          672          18.181818
YearStart                           0           0.000000
LocationDesc                        0           0.000000
Class                               0           0.000000
Topic                               0           0.000000
Question                            0           0.000000
Stratification1                     0           0.000000
TopicID                             0           0.000000

In [102]:
missing_df = missing_values_table(cognitive_df_clean)
missing_columns = list(
    missing_df[missing_df['% of Total Values'] > 50.0].index)
print('We will remove {} column(s).'.format(missing_columns))
cognitive_df_clean = cognitive_df_clean.drop(columns=list(missing_columns))

The DataFrame has 13 columns.
There are 13 columns that have missing values
We will remove ['Stratification2'] column(s).

**Check `NaN`s in Data_Value (Percent of People with Dementia )**

>The other problem is having many missing/empty values in proportion of people with cognitive impairement `Data_Value` in each state. 

>After a little bit of work noticed that in year `2011 and 2016` `Data_Value` column was not good enough to represent almost all states. In other words, about $72\%$ and $53\%$  of the Data_Value respectively, -the percent of the patients with cognitive impairement - was not reported and the data is not available. So we have to `remove` the year of `2011 and 2016` from our analysis. We now have of years 2015 data to work on.

>Next, we should be able fill in those missing values in year 2015 with mean value obtained from age group within each state. We apply transform method to do this in groups.

In [103]:
# Initialize year dataframes
year11 = cognitive_df.loc[cognitive_df_clean['YearStart'] == 2011]
year15 = cognitive_df.loc[cognitive_df_clean['YearStart'] == 2015]
year16 = cognitive_df.loc[cognitive_df_clean['YearStart'] == 2016]

# Compute the ratio of missing number of reports in each year
missing_ratio11 = year11['Data_Value'].isnull().sum() / len(year11)
missing_ratio15 = year15['Data_Value'].isnull().sum() / len(year15)
missing_ratio16 = year16['Data_Value'].isnull().sum() / len(year16)

# Combine the results
data = {'Missing_Ratio2011': missing_ratio11,
        'Missing_Ratio2015': missing_ratio15,
        'Missing_Ratio2016': missing_ratio16}

In [104]:
def make_table(data, col_name):
    # Make a table of the results
    df = pd.DataFrame(data=list(data.values()), columns=[
                      col_name], index=list(data.keys()))
    return df.sort_values(by=col_name, ascending=False)


make_table(data, 'Missing_Ratios')

                   Missing_Ratios
Missing_Ratio2011        0.729167
Missing_Ratio2016        0.567235
Missing_Ratio2015        0.300189

In [105]:
# Drop 2011 and 2016 now
cognitive_df_15 = cognitive_df_clean[(cognitive_df_clean['YearStart'] != 2011) & (
    cognitive_df_clean['YearStart'] != 2016)]
print('This is all the data:', cognitive_df_15.shape)

# Let's check how many NaN is there still
cognitive_df_15['Data_Value'].fillna(np.nan, inplace=True)
print('This shows where Data_Value is null: ',
      cognitive_df_15[cognitive_df_15['Data_Value'].isnull()].shape)

This is all the data: (2112, 12)
This shows where Data_Value is null:  (634, 12)

/anaconda3/lib/python3.5/site-packages/pandas/core/generic.py:5434: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [106]:
# Prepare a list of duplicate or unneccesary State Names that will be dropped from Locations
duplicates = ['United States, DC & Territories',
              'Midwest', 'Northeast', 'South', 'West']
duplicates_df = cognitive_df_15[cognitive_df_15.LocationDesc.isin(duplicates)]

# Drop and save it
cognitive_df_15 = cognitive_df_15.drop(
    duplicates_df.index, axis=0).copy(deep=True)

# Drop States that does not have any data reported. Sum Data_Value over all groups to see any state if 0
state_check = cognitive_df_15.groupby(['LocationDesc', 'Stratification1'])[
    'Data_Value'].sum().reset_index()
states_null = state_check[state_check['Data_Value'] == 0]
state_names_drop = states_null.LocationDesc.unique().tolist()
state_names_drop_df = cognitive_df_15[cognitive_df_15.LocationDesc.isin(
    state_names_drop)]

# Drop and save it
cognitive_df_15 = cognitive_df_15.drop(
    state_names_drop_df.index, axis=0).copy(deep=True)

# Fill every remaining Nan in Data_Value Column by age_group mean in each state for each age group in Percentages column
cognitive_df_15.loc[:, 'Percentages'] = np.round(cognitive_df_15.groupby(
    ['LocationDesc', 'Stratification1'])['Data_Value'].transform(lambda x: x.fillna(x.mean())), 2)

In [107]:
cognitive_df_15.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1632 entries, 28499 to 42646
Data columns (total 13 columns):
YearStart                1632 non-null int64
LocationDesc             1632 non-null object
Class                    1632 non-null object
Topic                    1632 non-null object
Question                 1632 non-null object
Data_Value               1107 non-null float64
Low_Confidence_Limit     1107 non-null float64
High_Confidence_Limit    1107 non-null float64
Stratification1          1632 non-null object
TopicID                  1632 non-null object
Longitude                1632 non-null float64
Latitude                 1632 non-null float64
Percentages              1632 non-null float64
dtypes: float64(6), int64(1), object(6)
memory usage: 178.5+ KB

In [108]:
cognitive_df_15 = cognitive_df_15.rename(
    {'Stratification1': 'Age_Groups'}, axis=1)
cognitive_df_15.head()

,YearStart,LocationDesc,Class,Topic,Question,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,Age_Groups,TopicID,Longitude,Latitude,Percentages
28499,2015,Alabama,Cognitive Decline,Subjective cognitive decline or memory loss am...,Percentage of older adults who reported subjec...,13.0,10.4,16.2,50-54 years,TCC01,32.840571,-86.631861,13.0
28500,2015,Alaska,Cognitive Decline,Subjective cognitive decline or memory loss am...,Percentage of older adults who reported subjec...,NaN,NaN,NaN,50-54 years,TCC01,64.845080,-147.722059,8.7
28501,2015,Arizona,Cognitive Decline,Subjective cognitive decline or memory loss am...,Percentage of older adults who reported subjec...,14.6,11.1,19.0,50-54 years,TCC01,34.865970,-111.763811,14.6
28502,2015,Arkansas,Cognitive Decline,Subjective cognitive decline or memory loss am...,Percentage of older adults who reported subjec...,18.4,12.7,25.9,50-54 years,TCC01,34.748650,-92.274491,18.4
28504,2015,California,Cognitive Decline,Subjective cognitive decline or memory loss am...,Percentage of older adults who reported subjec...,11.0,7.0,17.1,50-54 years,TCC01,37.638640,-121.000000,11.0